"""Tests for the scope storage renderer and ``kioku-mesh config render-storages``.

No Zenoh session is involved: the renderer is pure text plus a read-only SQLite
scan, so these tests invoke ``cli_main`` directly against files in ``tmp_path``.
"""

from __future__ import annotations

from pathlib import Path
import sqlite3

import pytest

from kioku_mesh.__main__ import main as cli_main
from kioku_mesh.core.scope import resolve_storage_scopes
from kioku_mesh.core.storage_render import LEGACY_SOURCE_NAME
from kioku_mesh.core.storage_render import missing_scope_counts
from kioku_mesh.core.storage_render import render_storage_entries
from kioku_mesh.core.storage_render import replace_storages
from kioku_mesh.core.storage_render import StorageRenderError

# The pre-split shape, with TLS and a hand-added key: what an upgrading host has.
PRE_SPLIT_CONFIG = """\
// Generated by `kioku-mesh init --mode hub` — hub: spokes dial in. (mTLS enabled)

{
  mode: "router",

  listen: {
    endpoints: [
      "tls/127.0.0.1:7447",
      "tls/192.168.128.11:7447",
    ],
  },

  connect: {
    endpoints: [],
  },

  transport: {
    link: {
      tls: {
        root_ca_certificate: "/home/u/.config/kioku-mesh/tls/ca.pem",
        enable_mtls: true,
        verify_name_on_connect: true,
        listen_private_key: "/home/u/.config/kioku-mesh/tls/peer-key.pem",
        listen_certificate: "/home/u/.config/kioku-mesh/tls/peer.pem",
        connect_private_key: "/home/u/.config/kioku-mesh/tls/peer-key.pem",
        connect_certificate: "/home/u/.config/kioku-mesh/tls/peer.pem",
      },
    },
  },

  timestamping: {
    enabled: { router: true, peer: true, client: true },
  },

  // hand-added after init; must survive the storage rewrite
  scouting: {
    multicast: { enabled: false },
  },

  plugins: {
    storage_manager: {
      volumes: {
        rocksdb: {},
      },
      storages: {
        agent_mem: {
          key_expr: "mem/**",
          strip_prefix: "mem",
          volume: {
            id: "rocksdb",
            dir: "agent_mem",
            create_db: true,
          },
        },
      },
    },
  },
}
"""


@pytest.fixture
def host_config(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Redirect XDG_CONFIG_HOME and write a pre-split zenohd.json5 into it."""
    monkeypatch.setenv('XDG_CONFIG_HOME', str(tmp_path / 'xdg'))
    cfg_dir = tmp_path / 'xdg' / 'kioku-mesh'
    cfg_dir.mkdir(parents=True)
    (cfg_dir / 'zenohd.json5').write_text(PRE_SPLIT_CONFIG, encoding='utf-8')
    return cfg_dir / 'zenohd.json5'


def _set_scopes(cfg_path: Path, scopes: list[str]) -> None:
    body = 'storage_scopes:\n' + ''.join(f'  - {s}\n' for s in scopes)
    (cfg_path.parent / 'config.yaml').write_text(body, encoding='utf-8')


def _make_index(path: Path, rows: list[tuple[str, str]]) -> Path:
    con = sqlite3.connect(path)
    con.execute('CREATE TABLE obs_index (observation_id TEXT PRIMARY KEY, payload_json TEXT)')
    for i, (visibility, scope_id) in enumerate(rows):
        payload = f'{{"visibility": "{visibility}", "scope_id": "{scope_id}"}}'
        con.execute('INSERT INTO obs_index VALUES (?, ?)', (f'obs{i}', payload))
    con.commit()
    con.close()
    return path


def test_mesh_storage_uses_clean_dir_and_keeps_strip_prefix() -> None:
    """B1: a new empty dir, and ``mem`` (not ``mem/mesh``) as the strip prefix."""
    entries = render_storage_entries(resolve_storage_scopes(['mesh']))
    assert 'key_expr: "mem/mesh/**"' in entries
    assert 'strip_prefix: "mem",' in entries
    assert 'dir: "mesh",' in entries
    assert 'agent_mem' not in entries


def test_scoped_storages_get_their_own_dirs() -> None:
    entries = render_storage_entries(resolve_storage_scopes(['mesh', 'user/hwata', 'team/sbgisen']))
    assert 'user_hwata_store' in entries
    assert 'strip_prefix: "mem/user/hwata"' in entries
    assert 'dir: "team_sbgisen",' in entries
    # Replication parameters must be identical across peers, so every storage
    # carries the same block.
    assert entries.count('propagation_delay: 250,') == 3


def test_transitional_keeps_the_broad_store_as_reput_source() -> None:
    entries = render_storage_entries(resolve_storage_scopes(['mesh']), include_legacy_source=True)
    assert f'{LEGACY_SOURCE_NAME}: {{' in entries
    assert 'key_expr: "mem/**"' in entries
    assert 'dir: "agent_mem",' in entries


def test_replace_storages_preserves_everything_else() -> None:
    """Golden config: endpoints, TLS and unknown keys are byte-identical."""
    rendered = replace_storages(PRE_SPLIT_CONFIG, render_storage_entries(resolve_storage_scopes(['mesh'])))
    before, after = PRE_SPLIT_CONFIG.split('      storages: {'), rendered.split('      storages: {')
    assert before[0] == after[0]
    # Nothing outside the storages block moved: the tail after the block closes
    # is unchanged too.
    assert before[1].split('      },\n')[-1] == after[1].split('      },\n')[-1]
    for line in (
        '"tls/127.0.0.1:7447",',
        '"tls/192.168.128.11:7447",',
        'root_ca_certificate: "/home/u/.config/kioku-mesh/tls/ca.pem",',
        'enable_mtls: true,',
        'connect_certificate: "/home/u/.config/kioku-mesh/tls/peer.pem",',
        'multicast: { enabled: false },',
    ):
        assert rendered.count(line) == PRE_SPLIT_CONFIG.count(line) == 1
    assert 'agent_mem' not in rendered
    assert 'mesh_store' in rendered


def test_replace_storages_rejects_a_config_without_storages() -> None:
    with pytest.raises(StorageRenderError):
        replace_storages('{ mode: "router" }\n', 'x')


def test_missing_scope_counts_flags_scopes_with_no_storage(tmp_path: Path) -> None:
    db = _make_index(tmp_path / 'index.db', [('mesh', ''), ('user', 'hwata'), ('team', 'sbgisen'), ('', '')])
    missing = missing_scope_counts(resolve_storage_scopes(['mesh']), db)
    # legacy rows belong to migrate-visibility, not to the renderer.
    assert dict(missing) == {'user/hwata': 1, 'team/sbgisen': 1}
    assert missing_scope_counts(resolve_storage_scopes(['mesh', 'user/hwata', 'team/sbgisen']), db) == {}


def test_missing_scope_counts_tolerates_a_missing_database(tmp_path: Path) -> None:
    assert missing_scope_counts(resolve_storage_scopes(['mesh']), tmp_path / 'nope.db') == {}


def test_dry_run_writes_nothing_and_warns_about_partial_cutover(
    host_config: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    _set_scopes(host_config, ['mesh', 'user/hwata'])
    assert cli_main(['config', 'render-storages', '--dry-run', '--db', str(host_config.parent / 'none.db')]) == 0
    assert host_config.read_text(encoding='utf-8') == PRE_SPLIT_CONFIG
    out = capsys.readouterr().out
    assert '+        user_hwata_store: {' in out
    assert 'never backfilled' in out
    assert 'half-applied' in out


def test_apply_rewrites_only_the_storages_block(host_config: Path) -> None:
    _set_scopes(host_config, ['mesh', 'team/sbgisen'])
    assert cli_main(['config', 'render-storages', '--apply', '--db', str(host_config.parent / 'none.db')]) == 0
    body = host_config.read_text(encoding='utf-8')
    assert 'team_sbgisen_store' in body
    assert 'agent_mem' not in body
    assert '"tls/192.168.128.11:7447",' in body
    assert 'multicast: { enabled: false },' in body


def test_apply_refuses_while_stored_scopes_have_no_storage(
    host_config: Path, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Step 7: an upgrading host must not silently become mesh-only."""
    db = _make_index(tmp_path / 'index.db', [('user', 'hwata'), ('user', 'hwata')])
    assert cli_main(['config', 'render-storages', '--apply', '--db', str(db)]) == 1
    assert host_config.read_text(encoding='utf-8') == PRE_SPLIT_CONFIG
    err = capsys.readouterr().err
    assert 'user/hwata: 2 observation(s)' in err

    assert cli_main(['config', 'render-storages', '--apply', '--acknowledge-missing-scopes', '--db', str(db)]) == 0
    assert 'mesh_store' in host_config.read_text(encoding='utf-8')


def test_render_storages_reports_an_invalid_scope_list(host_config: Path, capsys: pytest.CaptureFixture[str]) -> None:
    _set_scopes(host_config, ['user/hwata'])  # mesh missing
    assert cli_main(['config', 'render-storages', '--dry-run']) == 2
    assert 'storage_scopes' in capsys.readouterr().err


def test_render_storages_needs_an_existing_config(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv('XDG_CONFIG_HOME', str(tmp_path / 'empty'))
    assert cli_main(['config', 'render-storages', '--dry-run']) == 1
